

taco:
  orders:
    pageSize: 10

  discount:
    codes:
      abcdef: 10

#logging:
#  level:
#  tacos: DEBUG


#All it takes to make a profile active is to include it
#in the list of profile names given to the spring.profiles.active property.

#For example, you could set it in application.yml like this:

#spring:
# profiles:
#   active:
#     - prod
#     - audit
#     - ha

#I recommend that you set the active profile(s) with environment variables.
#On the production environment, you would set SPRING_PROFILES_ACTIVE like this:

#% export SPRING_PROFILES_ACTIVE=prod
#% export SPRING_PROFILES_ACTIVE=prod,audit,ha

#If you’re running the application as an executable JAR file, you might also set the
#active profile with a command-line argument like this:

#% java -jar taco-cloud.jar --spring.profiles.active=prod


---

#Profiles are a type of conditional configuration
#where different beans, configuration classes, and configuration
#properties are applied or ignored based on what profiles are active at runtime

#let’s say that for development and debugging purposes, you want to
#use the embedded H2 database, and you want the logging levels for the Taco Cloud
#code to be set to DEBUG.
#But in production, you want to use an external MySQL database
#and set the logging levels to WARN

#In the development situation, it’s easy
#enough to not set any data-source properties and get the autoconfigured H2 database.


#One way to define profile-specific properties is to create yet another YAML or properties
#file containing only the properties for production. The name of the file should follow
#this convention:

#   application-{profile name}.yml or
#   application-{profile name}.properties.

#Then you can specify the configuration properties appropriate to that profile. For
#example, you could create a new file named application-prod.yml that contains the
#following properties:

#Another way to specify profile-specific properties works only with YAML configuration.
#It involves
#     placing profile-specific properties alongside non-profiled properties in application.yml,
#     separated by three hyphens ---
#     and the spring.profiles property to name the profile.


spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacodb
    password: tacopassword

logging:
  level:
    tacos: WARN



#it’ll start on a randomly chosen available port
#server:
#  port: 0

#it’s simpler to configure the URL and credentials for your database
#via configuration properties

# spring:
#   datasource:
#     url: jdbc:mysql://localhost/tacocloud
#     username: tacodb
#     password: tacopassword
#     driver-class-name: com.mysql.jdbc.Driver

#If you set the spring.datasource.jndi-name property, the other data source connection
#properties (if set) are ignored

#     jndi-name: java:/comp/env/jdbc/tacoCloudDS

#way to specify the database
#initialization scripts to run when the application starts.

#     schema:
#       - order-schema.sql
#       - ingredient-schema.sql
#       - taco-schema.sql
#       - user-schema.sql
#      data:
#        - ingredients.sql


